
CREATE DATABASE PRESTAMOS
USE PRESTAMOS



CREATE TABLE VISTAS(ID_MENUS INT,NOMBRE_MENU VARCHAR(50), ICONO VARCHAR(50), PRIMARY KEY(ID_MENUS)
)

GO

CREATE TABLE SUB_VISTAS(ID_SUB_MENUS INT,ID_MENUS INT, NOMBRE_SUB_MENU VARCHAR(50),NOMBRE_FORMA VARCHAR(50),
PRIMARY KEY (ID_SUB_MENUS),FOREIGN KEY (ID_MENUS) REFERENCES MENUS(ID_MENUS)
)
GO


CREATE TABLE ROLES(ID_ROL INT,NOMBRE_ROL VARCHAR(50),PRIMARY KEY(ID_ROL)
)
GO


CREATE TABLE PERMISOS_USUARIOS(ID_PERMISOS INT, ID_ROL INT,ID_SUB_MENUS INT,
ACTIVO BIT,PRIMARY KEY (ID_PERMISOS), FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL),
FOREIGN KEY(ID_SUB_MENUS) REFERENCES SUB_MENUS (ID_SUB_MENUS)
)
GO

CREATE TABLE AREAS (NO_AREA INT, NOMBRE_AREA VARCHAR(50),PRIMARY KEY(NO_AREA)
)
GO

CREATE TABLE PUESTOS(NO_PUESTO INT, ID_AREA INT, NOMBRE_PUESTOS VARCHAR(60), FOREIGN KEY(ID_AREA) REFERENCES AREAS(NO_AREA),
PRIMARY KEY(NO_PUESTO)
)
GO

CREATE TABLE EMPLEADOS(ID_EMPLEADO INT, NOMBRE_EMPLEADO VARCHAR(70),NOMBRE_USUARIO varchar (60),SUELDO_EMPLEADO INT,
CLAVE_EMPLEADO VARCHAR(50),DOMICILIO_EMPLEADO VARCHAR(60),FECHA_NACIMIENTO DATE, ID_ROL INT,ID_PUESTO INT, PRIMARY KEY(ID_EMPLEADO), FOREIGN KEY(ID_ROL)
REFERENCES ROLES(ID_ROL), FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(NO_PUESTO)
)
GO

CREATE TABLE PRESTAMO(ID_PRESTAMO INT, MONTO_PRESTAMO INT, FECHA_PRESTAMO DATE,ID_EMPLEADO INT,
PRIMARY KEY(ID_PRESTAMO), FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
)
GO

select * from EMPLEADOS